In [1]:
# Dependencies
import pandas as pd
import requests
from config import api_key
from pprint import pprint

#file path to open CSV
movie_file ="Resources/netflix_titles.csv"

In [2]:
# Read and display the CSV with Pandas

movie_file_df = pd.read_csv(movie_file)
movie_file_df.head()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,81145628,Movie,Norm of the North: King Sized Adventure,"Richard Finn, Tim Maltby","Alan Marriott, Andrew Toth, Brian Dobson, Cole...","United States, India, South Korea, China","September 9, 2019",2019,TV-PG,90 min,"Children & Family Movies, Comedies",Before planning an awesome wedding for his gra...
1,80117401,Movie,Jandino: Whatever it Takes,NaN,Jandino Asporaat,United Kingdom,"September 9, 2016",2016,TV-MA,94 min,Stand-Up Comedy,Jandino Asporaat riffs on the challenges of ra...
2,70234439,TV Show,Transformers Prime,NaN,"Peter Cullen, Sumalee Montano, Frank Welker, J...",United States,"September 8, 2018",2013,TV-Y7-FV,1 Season,Kids' TV,"With the help of three human allies, the Autob..."
3,80058654,TV Show,Transformers: Robots in Disguise,NaN,"Will Friedle, Darren Criss, Constance Zimmer, ...",United States,"September 8, 2018",2016,TV-Y7,1 Season,Kids' TV,When a prison ship crash unleashes hundreds of...
4,80125979,Movie,#realityhigh,Fernando Lebrija,"Nesta Cooper, Kate Walsh, John Michael Higgins...",United States,"September 8, 2017",2017,TV-14,99 min,Comedies,When nerdy high schooler Dani finally attracts...

In [3]:
base_url = f"http://www.omdbapi.com/?apikey={api_key}&t="

In [ ]:
titles= movie_file_df["title"]
Genres = []
awards = []
released_date = []
imdb_ratings = []
rt_ratings = []

#print(titles)
i = 0
for title in titles:
    i= i+1
    #if i <=16:
    url = base_url +title   
    movie = requests.get(url).json()
        #pprint(movie)

    try:
        Genres.append(movie["Genre"])
    except:
        Genres.append("NaN")
    try:
         awards.append(movie["Awards"])
    except:
        awards.append("NaN")   
    try:
        released_date.append(movie["Released"])
    except:
        released_date.append("NaN") 
    try:
        imdb_ratings.append(movie["Ratings"][0]["Value"])
    except:
        imdb_ratings.append("0")      

    try:
        rt_ratings.append(movie["Ratings"][1]["Value"])
    except:
        rt_ratings.append("0")
    
       
        
print (Genres)
print(awards)
print(released_date)
print(imdb_ratings)
print(rt_ratings)

In [ ]:
 #add the information extracted to the DataFrame
print(len(imdb_ratings))
movie_file_df["IMDB rating"] = imdb_ratings
movie_file_df["Rotten Tomatoes rating"] = rt_ratings
movie_file_df["Award"] = awards
movie_file_df["Released Date"] = released_date

In [ ]:
movie_file_df.dtypes

In [ ]:
 movie_file_df.rename(columns ={"release_year": "Netflix release year"}, inplace =True)

In [ ]:
pd.set_option('display.max_columns', 300)
pd.set_option('display.max_rows', 10000)
movie_file_df

In [ ]:
movie_file_df["IMDB rating"]= movie_file_df["IMDB rating"].str.split("/").str[0]

In [ ]:
movie_file_df

In [ ]:
movie_file_df["IMDB rating"] = movie_file_df["IMDB rating"].astype(float)

In [ ]:
movie_file_df.dtypes